services:
  server:
    build:
      context: .
    ports:
      - 8000:8000

    volumes:
      - /Users/a.gazzaev/Desktop/classification_model/experiments:/classification
      - /Users/a.gazzaev/Desktop/lab1/classification_model/data:/data